"""ADK agent generated by scaffolder."""

from __future__ import annotations

import datetime
from zoneinfo import ZoneInfo

from google.adk.agents import Agent


def get_weather(city: str) -> dict:
    if city.lower() == "new york":
        return {
            "status": "success",
            "report": (
                "The weather in New York is sunny with a temperature of 25°C " "(77°F)."
            ),
        }
    return {
        "status": "error",
        "error_message": (f"Weather information for '{city}' is not " f"available."),
    }


def get_current_time(city: str) -> dict:
    if city.lower() == "new york":
        tz_identifier = "America/New_York"
    else:
        return {
            "status": "error",
            "error_message": (f"Sorry, I don't have timezone information for {city}."),
        }
    tz = ZoneInfo(tz_identifier)
    now = datetime.datetime.now(tz)
    report = (
        f"The current time in {city} is " f"{now.strftime('%Y-%m-%d %H:%M:%S %Z%z')}"
    )
    return {"status": "success", "report": report}


root_agent = Agent(
    name="demo2",
    model="gemini-2.0-flash",
    description=("Agent that answers questions about the time and weather in a city."),
    instruction=(
        "You are a helpful agent who can answer user questions about the "
        "time and weather in a city."
    ),
    tools=[get_weather, get_current_time],
)
